/** PostgreSQL DDL（与 SQLite schema 对齐，供双写与只读副本） */
export const PG_SCHEMA_STATEMENTS: string[] = [
  `CREATE TABLE IF NOT EXISTS system_meta (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at BIGINT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS deployed_contract (
    id SERIAL PRIMARY KEY,
    chain_id INTEGER NOT NULL,
    deployer_address TEXT NOT NULL,
    contract_address TEXT NOT NULL UNIQUE,
    tx_hash TEXT NOT NULL,
    block_number INTEGER NOT NULL,
    deploy_time BIGINT NOT NULL,
    is_token INTEGER DEFAULT 0,
    token_name TEXT,
    token_symbol TEXT,
    token_decimals INTEGER,
    total_supply TEXT,
    status TEXT NOT NULL DEFAULT 'deployed_no_liquidity',
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS token_pair (
    id SERIAL PRIMARY KEY,
    chain_id INTEGER NOT NULL,
    token_address TEXT NOT NULL,
    pair_address TEXT NOT NULL,
    token0 TEXT NOT NULL,
    token1 TEXT NOT NULL,
    quote_token TEXT NOT NULL,
    quote_symbol TEXT,
    dex_name TEXT DEFAULT 'PancakeSwap',
    created_tx_hash TEXT,
    created_block INTEGER,
    created_at BIGINT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS token_event (
    id SERIAL PRIMARY KEY,
    chain_id INTEGER NOT NULL,
    token_address TEXT NOT NULL,
    event_type TEXT NOT NULL,
    tx_hash TEXT NOT NULL,
    log_index INTEGER NOT NULL DEFAULT 0,
    block_number INTEGER NOT NULL,
    event_time BIGINT NOT NULL,
    from_address TEXT,
    to_address TEXT,
    trader TEXT,
    token_amount TEXT,
    quote_amount TEXT,
    price DOUBLE PRECISION DEFAULT 0,
    pair_address TEXT,
    amount_usd DOUBLE PRECISION DEFAULT 0,
    balance_after TEXT,
    quote_balance_after TEXT,
    UNIQUE (chain_id, tx_hash, log_index, token_address)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_pg_event_token_time ON token_event (chain_id, token_address, event_time DESC)`,
  `CREATE TABLE IF NOT EXISTS token_holder (
    id SERIAL PRIMARY KEY,
    chain_id INTEGER NOT NULL,
    token_address TEXT NOT NULL,
    holder_address TEXT NOT NULL,
    balance TEXT NOT NULL DEFAULT '0',
    balance_percent DOUBLE PRECISION DEFAULT 0,
    last_active_time BIGINT,
    address_tag TEXT,
    UNIQUE (chain_id, token_address, holder_address)
  )`,
  `CREATE TABLE IF NOT EXISTS token_address_stat (
    id SERIAL PRIMARY KEY,
    chain_id INTEGER NOT NULL,
    token_address TEXT NOT NULL,
    wallet_address TEXT NOT NULL,
    buy_count INTEGER DEFAULT 0,
    sell_count INTEGER DEFAULT 0,
    transfer_in_count INTEGER DEFAULT 0,
    transfer_out_count INTEGER DEFAULT 0,
    total_buy_token TEXT DEFAULT '0',
    total_sell_token TEXT DEFAULT '0',
    total_buy_value DOUBLE PRECISION DEFAULT 0,
    total_sell_value DOUBLE PRECISION DEFAULT 0,
    current_balance TEXT DEFAULT '0',
    is_cleared INTEGER DEFAULT 0,
    last_trade_time BIGINT,
    first_buy_time BIGINT,
    staking_balance TEXT DEFAULT '0',
    UNIQUE (chain_id, token_address, wallet_address)
  )`,
  `CREATE TABLE IF NOT EXISTS token_market_cache (
    chain_id INTEGER NOT NULL DEFAULT 56,
    token_address TEXT NOT NULL,
    symbol TEXT,
    price_usd DOUBLE PRECISION DEFAULT 0,
    price_change_5m DOUBLE PRECISION DEFAULT 0,
    price_change_15m DOUBLE PRECISION DEFAULT 0,
    price_change_1h DOUBLE PRECISION DEFAULT 0,
    price_change_24h DOUBLE PRECISION DEFAULT 0,
    high_24h DOUBLE PRECISION DEFAULT 0,
    low_24h DOUBLE PRECISION DEFAULT 0,
    volume_24h_usd DOUBLE PRECISION DEFAULT 0,
    liquidity_usd DOUBLE PRECISION DEFAULT 0,
    token_reserve TEXT,
    quote_reserve TEXT,
    holder_count INTEGER DEFAULT 0,
    liquidity_change_24h DOUBLE PRECISION DEFAULT 0,
    liquidity_change_7d DOUBLE PRECISION DEFAULT 0,
    updated_at BIGINT NOT NULL,
    PRIMARY KEY (chain_id, token_address)
  )`,
  `CREATE TABLE IF NOT EXISTS token_price_snapshot (
    id SERIAL PRIMARY KEY,
    chain_id INTEGER NOT NULL,
    token_address TEXT NOT NULL,
    price_usd DOUBLE PRECISION NOT NULL,
    liquidity_usd DOUBLE PRECISION DEFAULT 0,
    token_reserve TEXT,
    quote_reserve TEXT,
    recorded_at BIGINT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS alert_log (
    id SERIAL PRIMARY KEY,
    chain_id INTEGER NOT NULL DEFAULT 56,
    alert_type TEXT NOT NULL,
    token_address TEXT,
    pair_address TEXT,
    tx_hash TEXT,
    message TEXT,
    channel TEXT DEFAULT 'telegram',
    send_status TEXT,
    level TEXT DEFAULT 'MEDIUM',
    wallet_address TEXT,
    amount_usd DOUBLE PRECISION,
    handled INTEGER DEFAULT 0,
    created_at BIGINT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS sync_status (
    id SERIAL PRIMARY KEY,
    chain_id INTEGER NOT NULL,
    token_address TEXT NOT NULL,
    sync_type TEXT NOT NULL,
    start_block INTEGER NOT NULL DEFAULT 0,
    last_synced_block INTEGER NOT NULL DEFAULT 0,
    latest_block INTEGER,
    confirm_blocks INTEGER NOT NULL DEFAULT 3,
    status TEXT NOT NULL DEFAULT 'RUNNING',
    error_message TEXT,
    lag_blocks INTEGER DEFAULT 0,
    heartbeat_at BIGINT,
    updated_at BIGINT NOT NULL,
    UNIQUE (chain_id, token_address, sync_type)
  )`,
  `CREATE TABLE IF NOT EXISTS listener_service (
    service_name TEXT PRIMARY KEY,
    status TEXT NOT NULL DEFAULT 'RUNNING',
    heartbeat_at BIGINT NOT NULL,
    latest_block INTEGER,
    lag_blocks INTEGER DEFAULT 0,
    error_message TEXT,
    updated_at BIGINT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS raw_events (
    id SERIAL PRIMARY KEY,
    chain_id INTEGER NOT NULL,
    token_address TEXT,
    contract_address TEXT NOT NULL,
    event_name TEXT NOT NULL,
    tx_hash TEXT NOT NULL,
    log_index INTEGER NOT NULL DEFAULT 0,
    block_number INTEGER NOT NULL,
    block_hash TEXT,
    block_time BIGINT NOT NULL,
    topic0 TEXT,
    topics TEXT,
    data TEXT,
    decoded_data TEXT,
    from_address TEXT,
    to_address TEXT,
    processed INTEGER NOT NULL DEFAULT 0,
    process_status TEXT NOT NULL DEFAULT 'pending',
    error_message TEXT,
    process_retry_count INTEGER NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    UNIQUE (chain_id, tx_hash, log_index)
  )`,
  `CREATE TABLE IF NOT EXISTS sync_failed_blocks (
    id SERIAL PRIMARY KEY,
    chain_id INTEGER NOT NULL,
    token_address TEXT NOT NULL,
    sync_type TEXT NOT NULL,
    block_from INTEGER NOT NULL,
    block_to INTEGER NOT NULL,
    error_message TEXT,
    retry_count INTEGER NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    UNIQUE (chain_id, token_address, sync_type, block_from, block_to)
  )`,
  `CREATE TABLE IF NOT EXISTS holder_profiles (
    id SERIAL PRIMARY KEY,
    chain_id INTEGER NOT NULL,
    token_address TEXT NOT NULL,
    wallet_address TEXT NOT NULL,
    wallet_balance TEXT NOT NULL DEFAULT '0',
    staking_balance TEXT NOT NULL DEFAULT '0',
    total_balance TEXT NOT NULL DEFAULT '0',
    balance_usd DOUBLE PRECISION NOT NULL DEFAULT 0,
    holding_percent DOUBLE PRECISION NOT NULL DEFAULT 0,
    buy_count INTEGER NOT NULL DEFAULT 0,
    sell_count INTEGER NOT NULL DEFAULT 0,
    total_buy_amount TEXT NOT NULL DEFAULT '0',
    total_buy_usd TEXT NOT NULL DEFAULT '0',
    total_sell_amount TEXT NOT NULL DEFAULT '0',
    total_sell_usd TEXT NOT NULL DEFAULT '0',
    net_buy_amount TEXT NOT NULL DEFAULT '0',
    net_buy_usd TEXT NOT NULL DEFAULT '0',
    avg_buy_price TEXT NOT NULL DEFAULT '0',
    avg_sell_price TEXT NOT NULL DEFAULT '0',
    realized_pnl TEXT NOT NULL DEFAULT '0',
    unrealized_pnl TEXT NOT NULL DEFAULT '0',
    total_pnl TEXT NOT NULL DEFAULT '0',
    roi TEXT NOT NULL DEFAULT '0',
    first_buy_time BIGINT,
    last_trade_time BIGINT,
    highest_balance TEXT NOT NULL DEFAULT '0',
    highest_balance_usd TEXT NOT NULL DEFAULT '0',
    is_contract INTEGER NOT NULL DEFAULT 0,
    is_whale INTEGER NOT NULL DEFAULT 0,
    is_super_whale INTEGER NOT NULL DEFAULT 0,
    is_staking_user INTEGER NOT NULL DEFAULT 0,
    is_cleared INTEGER NOT NULL DEFAULT 0,
    is_new_wallet INTEGER NOT NULL DEFAULT 0,
    holder_level TEXT NOT NULL DEFAULT 'small',
    liquidity_impact TEXT NOT NULL DEFAULT 'low',
    behavior_tags TEXT NOT NULL DEFAULT '[]',
    risk_tags TEXT NOT NULL DEFAULT '[]',
    lp_balance TEXT NOT NULL DEFAULT '0',
    lp_staked_balance TEXT NOT NULL DEFAULT '0',
    is_lp_staking_user INTEGER NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL,
    UNIQUE (chain_id, token_address, wallet_address)
  )`,
  `CREATE TABLE IF NOT EXISTS token_lp_staking_stat (
    chain_id INTEGER NOT NULL,
    token_address TEXT NOT NULL,
    pair_address TEXT NOT NULL,
    staking_contract TEXT NOT NULL,
    staking_pid INTEGER NOT NULL DEFAULT 0,
    total_lp_wallet TEXT NOT NULL DEFAULT '0',
    total_lp_staked TEXT NOT NULL DEFAULT '0',
    total_lp_supply TEXT NOT NULL DEFAULT '0',
    lp_staker_count INTEGER NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL,
    PRIMARY KEY (chain_id, token_address)
  )`,
  `CREATE TABLE IF NOT EXISTS token_staking_stat (
    chain_id INTEGER NOT NULL DEFAULT 56,
    token_address TEXT NOT NULL,
    total_staked TEXT DEFAULT '0',
    staker_count INTEGER DEFAULT 0,
    stake_24h TEXT DEFAULT '0',
    unstake_24h TEXT DEFAULT '0',
    updated_at BIGINT NOT NULL,
    PRIMARY KEY (chain_id, token_address)
  )`,
  `CREATE TABLE IF NOT EXISTS token_risk_scan (
    token_address TEXT PRIMARY KEY,
    owner_address TEXT,
    owner_renounced INTEGER DEFAULT 0,
    can_mint INTEGER DEFAULT 0,
    has_blacklist INTEGER DEFAULT 0,
    trading_disabled INTEGER DEFAULT 0,
    risk_level TEXT DEFAULT 'UNKNOWN',
    risk_flags TEXT,
    scanned_at BIGINT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS opportunity_score (
    token_address TEXT PRIMARY KEY,
    score INTEGER DEFAULT 50,
    trend TEXT DEFAULT 'NEUTRAL',
    bullish_signals TEXT,
    bearish_signals TEXT,
    risk_signals TEXT,
    updated_at BIGINT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS monitor_wallet (
    id SERIAL PRIMARY KEY,
    chain_id INTEGER NOT NULL,
    wallet_address TEXT NOT NULL UNIQUE,
    remark TEXT,
    enabled INTEGER DEFAULT 1,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS staking_record (
    id SERIAL PRIMARY KEY,
    chain_id INTEGER NOT NULL,
    token_address TEXT NOT NULL,
    wallet_address TEXT NOT NULL,
    action TEXT NOT NULL,
    amount TEXT NOT NULL,
    tx_hash TEXT NOT NULL,
    block_number INTEGER,
    event_time BIGINT NOT NULL,
    UNIQUE (chain_id, tx_hash, token_address, wallet_address, action)
  )`,
  `CREATE TABLE IF NOT EXISTS lp_staking_record (
    id SERIAL PRIMARY KEY,
    chain_id INTEGER NOT NULL,
    token_address TEXT NOT NULL,
    wallet_address TEXT NOT NULL,
    action TEXT NOT NULL,
    amount TEXT NOT NULL,
    tx_hash TEXT NOT NULL,
    log_index INTEGER NOT NULL DEFAULT 0,
    block_number INTEGER,
    event_time BIGINT NOT NULL,
    UNIQUE (chain_id, tx_hash, token_address, wallet_address, action)
  )`,
  `CREATE TABLE IF NOT EXISTS token_liquidity_stat (
    token_address TEXT PRIMARY KEY,
    pair_address TEXT,
    liquidity_usd DOUBLE PRECISION DEFAULT 0,
    lp_burned_pct DOUBLE PRECISION DEFAULT 0,
    lp_locked_pct DOUBLE PRECISION DEFAULT 0,
    lp_holder_count INTEGER DEFAULT 0,
    change_24h_pct DOUBLE PRECISION DEFAULT 0,
    change_7d_pct DOUBLE PRECISION DEFAULT 0,
    updated_at BIGINT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS address_label (
    id SERIAL PRIMARY KEY,
    chain_id INTEGER NOT NULL,
    token_address TEXT NOT NULL,
    wallet_address TEXT NOT NULL,
    label TEXT NOT NULL,
    confidence DOUBLE PRECISION DEFAULT 1,
    reason TEXT,
    updated_at BIGINT NOT NULL,
    UNIQUE (chain_id, token_address, wallet_address, label)
  )`,
  `CREATE TABLE IF NOT EXISTS addresses (
    chain_id INTEGER NOT NULL,
    address TEXT NOT NULL,
    address_type TEXT NOT NULL DEFAULT 'wallet',
    is_contract INTEGER NOT NULL DEFAULT 0,
    first_seen_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    PRIMARY KEY (chain_id, address)
  )`,
  `CREATE TABLE IF NOT EXISTS token_transactions (
    id SERIAL PRIMARY KEY,
    chain_id INTEGER NOT NULL,
    token_address TEXT NOT NULL,
    wallet_address TEXT NOT NULL,
    address_type TEXT NOT NULL DEFAULT 'wallet',
    is_contract INTEGER NOT NULL DEFAULT 0,
    tx_hash TEXT NOT NULL,
    log_index INTEGER NOT NULL DEFAULT 0,
    block_number INTEGER NOT NULL,
    block_time BIGINT NOT NULL,
    trade_type TEXT NOT NULL,
    side TEXT,
    token_amount TEXT NOT NULL DEFAULT '0',
    quote_amount TEXT NOT NULL DEFAULT '0',
    amount_usd DOUBLE PRECISION DEFAULT 0,
    price DOUBLE PRECISION DEFAULT 0,
    balance_after TEXT,
    quote_balance_after TEXT,
    staking_balance_after TEXT,
    buy_count_after INTEGER DEFAULT 0,
    sell_count_after INTEGER DEFAULT 0,
    from_address TEXT,
    to_address TEXT,
    pair_address TEXT,
    contract_address TEXT,
    UNIQUE (chain_id, tx_hash, log_index, trade_type)
  )`,
  `CREATE TABLE IF NOT EXISTS lp_notify_state (
    chain_id INTEGER NOT NULL,
    token_address TEXT NOT NULL,
    pair_address TEXT NOT NULL,
    notify_key TEXT NOT NULL,
    tx_hash TEXT,
    block_number INTEGER,
    notified_at BIGINT NOT NULL,
    PRIMARY KEY (chain_id, token_address, pair_address, notify_key)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_deployed_status ON deployed_contract (status)`,
  `CREATE INDEX IF NOT EXISTS idx_deployed_time ON deployed_contract (deploy_time DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_pair_token ON token_pair (token_address)`,
  `CREATE INDEX IF NOT EXISTS idx_holder_token ON token_holder (token_address, balance)`,
  `CREATE INDEX IF NOT EXISTS idx_event_type ON token_event (token_address, event_type)`,
  `CREATE INDEX IF NOT EXISTS idx_price_snap_token_time ON token_price_snapshot (token_address, recorded_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_staking_token ON staking_record (token_address, event_time DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_lp_staking_token ON lp_staking_record (token_address, event_time DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_lp_staking_wallet ON lp_staking_record (token_address, wallet_address, event_time DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_label_token ON address_label (token_address, label)`,
  `CREATE INDEX IF NOT EXISTS idx_sync_token ON sync_status (token_address, sync_type)`,
  `CREATE INDEX IF NOT EXISTS idx_raw_token_time ON raw_events (token_address, block_time DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_raw_processed ON raw_events (processed, process_status)`,
  `CREATE INDEX IF NOT EXISTS idx_holder_profiles_token ON holder_profiles (token_address, balance_usd DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_holder_profiles_level ON holder_profiles (token_address, holder_level)`,
  `CREATE INDEX IF NOT EXISTS idx_tx_token_time ON token_transactions (token_address, block_time DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_tx_wallet ON token_transactions (token_address, wallet_address, block_time DESC)`,
];

export const PG_SCHEMA_ALTERS: string[] = [
  'ALTER TABLE alert_log ADD COLUMN IF NOT EXISTS telegram_error TEXT',
  'ALTER TABLE alert_log ADD COLUMN IF NOT EXISTS retry_count INTEGER DEFAULT 0',
  'ALTER TABLE token_event ADD COLUMN IF NOT EXISTS amount_usd DOUBLE PRECISION DEFAULT 0',
  'ALTER TABLE token_event ADD COLUMN IF NOT EXISTS balance_after TEXT',
  'ALTER TABLE token_event ADD COLUMN IF NOT EXISTS quote_balance_after TEXT',
  'ALTER TABLE token_transactions ADD COLUMN IF NOT EXISTS quote_balance_after TEXT',
  'ALTER TABLE token_address_stat ADD COLUMN IF NOT EXISTS first_buy_time BIGINT',
  'ALTER TABLE holder_profiles ADD COLUMN IF NOT EXISTS lp_balance TEXT NOT NULL DEFAULT \'0\'',
  'ALTER TABLE holder_profiles ADD COLUMN IF NOT EXISTS lp_staked_balance TEXT NOT NULL DEFAULT \'0\'',
  'ALTER TABLE holder_profiles ADD COLUMN IF NOT EXISTS is_lp_staking_user INTEGER NOT NULL DEFAULT 0',
  'ALTER TABLE token_lp_staking_stat ADD COLUMN IF NOT EXISTS total_lp_supply TEXT NOT NULL DEFAULT \'0\'',
  `CREATE TABLE IF NOT EXISTS token_lp_staking_stat (
    chain_id INTEGER NOT NULL,
    token_address TEXT NOT NULL,
    pair_address TEXT NOT NULL,
    staking_contract TEXT NOT NULL,
    staking_pid INTEGER NOT NULL DEFAULT 0,
    total_lp_wallet TEXT NOT NULL DEFAULT '0',
    total_lp_staked TEXT NOT NULL DEFAULT '0',
    total_lp_supply TEXT NOT NULL DEFAULT '0',
    lp_staker_count INTEGER NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL,
    PRIMARY KEY (chain_id, token_address)
  )`,
  'ALTER TABLE token_address_stat ADD COLUMN IF NOT EXISTS last_buy_time BIGINT',
  'ALTER TABLE token_address_stat ADD COLUMN IF NOT EXISTS last_sell_time BIGINT',
  'ALTER TABLE token_address_stat ADD COLUMN IF NOT EXISTS staking_balance TEXT DEFAULT \'0\'',
  'ALTER TABLE holder_profiles ADD COLUMN IF NOT EXISTS address_type TEXT DEFAULT \'wallet\'',
  'ALTER TABLE holder_profiles ADD COLUMN IF NOT EXISTS last_buy_time BIGINT',
  'ALTER TABLE holder_profiles ADD COLUMN IF NOT EXISTS last_sell_time BIGINT',
  'ALTER TABLE sync_status ADD COLUMN IF NOT EXISTS lag_blocks INTEGER DEFAULT 0',
  'ALTER TABLE sync_status ADD COLUMN IF NOT EXISTS heartbeat_at BIGINT',
  'ALTER TABLE sync_status ADD COLUMN IF NOT EXISTS scan_interval_blocks INTEGER DEFAULT 2',
  'ALTER TABLE holder_profiles ADD COLUMN IF NOT EXISTS last_balance_checked_at BIGINT',
  `ALTER TABLE holder_profiles ADD COLUMN IF NOT EXISTS balance_source TEXT DEFAULT 'EVENT_ESTIMATED'`,
  'ALTER TABLE token_transactions DROP CONSTRAINT IF EXISTS token_transactions_chain_id_tx_hash_log_index_key',
  'DROP INDEX IF EXISTS token_transactions_chain_id_tx_hash_log_index_key',
  `CREATE UNIQUE INDEX IF NOT EXISTS uq_token_tx_chain_hash_log_trade
     ON token_transactions (chain_id, tx_hash, log_index, trade_type)`,
  'ALTER TABLE alert_log ADD COLUMN IF NOT EXISTS chain_id INTEGER NOT NULL DEFAULT 56',
  'ALTER TABLE token_market_cache ADD COLUMN IF NOT EXISTS chain_id INTEGER NOT NULL DEFAULT 56',
  'ALTER TABLE token_liquidity_stat ADD COLUMN IF NOT EXISTS chain_id INTEGER NOT NULL DEFAULT 56',
  'ALTER TABLE token_staking_stat ADD COLUMN IF NOT EXISTS chain_id INTEGER NOT NULL DEFAULT 56',
  'ALTER TABLE token_event DROP CONSTRAINT IF EXISTS token_event_tx_hash_log_index_token_address_key',
  'DROP INDEX IF EXISTS token_event_tx_hash_log_index_token_address_key',
  `CREATE UNIQUE INDEX IF NOT EXISTS uq_token_event_chain
     ON token_event (chain_id, tx_hash, log_index, token_address)`,
  'ALTER TABLE staking_record DROP CONSTRAINT IF EXISTS staking_record_tx_hash_token_address_wallet_address_action_key',
  `CREATE UNIQUE INDEX IF NOT EXISTS uq_staking_chain
     ON staking_record (chain_id, tx_hash, token_address, wallet_address, action)`,
  `CREATE TABLE IF NOT EXISTS lp_staking_record (
    id SERIAL PRIMARY KEY,
    chain_id INTEGER NOT NULL,
    token_address TEXT NOT NULL,
    wallet_address TEXT NOT NULL,
    action TEXT NOT NULL,
    amount TEXT NOT NULL,
    tx_hash TEXT NOT NULL,
    log_index INTEGER NOT NULL DEFAULT 0,
    block_number INTEGER,
    event_time BIGINT NOT NULL,
    UNIQUE (chain_id, tx_hash, token_address, wallet_address, action)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_lp_staking_token ON lp_staking_record (token_address, event_time DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_lp_staking_wallet ON lp_staking_record (token_address, wallet_address, event_time DESC)`,
  'ALTER TABLE lp_staking_record DROP CONSTRAINT IF EXISTS lp_staking_record_chain_id_tx_hash_log_index_token_address_key',
  `CREATE UNIQUE INDEX IF NOT EXISTS uq_lp_staking_tx_wallet_action
     ON lp_staking_record (chain_id, tx_hash, token_address, wallet_address, action)`,
  `DELETE FROM lp_staking_record a USING lp_staking_record b
   WHERE a.id > b.id
     AND a.chain_id = b.chain_id
     AND a.token_address = b.token_address
     AND a.wallet_address = b.wallet_address
     AND a.action = b.action
     AND a.tx_hash = b.tx_hash`,
  'ALTER TABLE token_pair DROP CONSTRAINT IF EXISTS token_pair_pair_address_key',
  `CREATE UNIQUE INDEX IF NOT EXISTS uq_pair_chain_addr
     ON token_pair (chain_id, pair_address)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS uq_market_cache_chain_token
     ON token_market_cache (chain_id, token_address)`,
  'ALTER TABLE token_staking_stat ADD COLUMN IF NOT EXISTS chain_id INTEGER NOT NULL DEFAULT 56',
  `CREATE UNIQUE INDEX IF NOT EXISTS uq_staking_stat_chain
     ON token_staking_stat (chain_id, token_address)`,
  'ALTER TABLE raw_events ADD COLUMN IF NOT EXISTS process_retry_count INTEGER NOT NULL DEFAULT 0',
  `CREATE INDEX IF NOT EXISTS idx_raw_pending_chain
     ON raw_events (chain_id, block_number, log_index)
     WHERE processed = 0 AND process_status = 'pending'`,
  `CREATE UNIQUE INDEX IF NOT EXISTS uq_sync_status_chain_task
     ON sync_status (chain_id, token_address, sync_type)`,
  `CREATE TABLE IF NOT EXISTS wallet_address_remark (
    chain_id INTEGER NOT NULL,
    token_address TEXT NOT NULL,
    wallet_address TEXT NOT NULL,
    remark TEXT NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    PRIMARY KEY (chain_id, token_address, wallet_address)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_wallet_remark_token
     ON wallet_address_remark (chain_id, token_address)`,
];
